### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TiAmo789** [Zerui18/zx02#3]
When using the main screen and lock screen separately, there may be issues with the lock screen interface!

Dopamine Jailbreak

[正在上传 237354912...]

**Comment by TiAmo789** [comment]
https://github.com/Zerui18/zx02/assets/127301869/3b1e6b85-4dc5-4804-abf8-b3979583f5bd

**Comment by Zerui18** [comment]
这应该是因为你的系统设置中homescreen和lockscreen用的是同样的壁纸，设置成不同的壁纸就能解决。

**Comment by TiAmo789** [comment]
感谢

**Comment by TiAmo789** [comment]
用你的办法可以解决，感谢
